### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [tuilakhanh/PlotSquared-Nukkit#1]
What does this version of P2 fix? Could you provide a README?

**Comment by tuilakhanh** [comment]
In the latest of nukkit build this plugin doesn`t load 

I think u should use future plot in the forum it more than stable than my plotsquared version

**Comment by ghost** [comment]
OK, thanks, but FuturePlot doesn't support plot merging yet... Until they support it, I'll use P2. (And I think I'll use your build xD)

**Comment by tuilakhanh** [comment]
This build. I didn't test yet. If you find any bug and error please tell me or help me fix it. My build always welcome your contribution ^_________^

**Comment by ghost** [comment]
I'll do :smile:

**Comment by ghost** [comment]
Closing this.
